/**
 * Benchmark runner.  `npm run bench`
 *
 * Runs the dataset through every CONFIGURED provider (stub always; anthropic/
 * openai/gemini when their *_API_KEY env var is set) and measures extraction
 * accuracy, confidence calibration, validation-failure rate, token usage, cost,
 * and latency. Writes bench/report.md + bench/report.json and prints a summary.
 *
 * Add a model later → set its API key and re-run. No code change.
 *   BENCH_PROVIDERS=stub,gemini  ANTHROPIC_API_KEY=...  npm run bench
 */

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { extract } from '../src/ai/extraction.ts';
import { SchemaValidationError } from '../src/ai/schema.ts';
import { createProvider, priceFor, type ProviderId } from '../src/ai/registry.ts';
import { InMemoryEvalSink } from '../src/eval/sink.ts';
import { DATASET } from './dataset.ts';
import { aggregate, scoreCase, type Aggregate, type CaseScore } from './score.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const KEY_ENV: Record<string, string> = { anthropic: 'ANTHROPIC_API_KEY', openai: 'OPENAI_API_KEY', gemini: 'GEMINI_API_KEY' };

interface Result {
  provider: ProviderId;
  model: string;
  agg: Aggregate;
  tokensIn: number;
  tokensOut: number;
  costUsd: number;
  latency: { meanMs: number; p50: number; p95: number };
  otherErrors: number;
}

function selectedProviders(env = process.env): ProviderId[] {
  if (env.BENCH_PROVIDERS) return env.BENCH_PROVIDERS.split(',').map((s) => s.trim() as ProviderId);
  const out: ProviderId[] = ['stub'];
  for (const p of ['anthropic', 'openai', 'gemini'] as ProviderId[]) if (env[KEY_ENV[p]!]) out.push(p);
  return out;
}

function percentile(sorted: number[], p: number): number {
  if (!sorted.length) return 0;
  const idx = Math.min(sorted.length - 1, Math.floor((p / 100) * sorted.length));
  return Math.round(sorted[idx]!);
}

async function runProvider(provider: ProviderId, env = process.env): Promise<Result> {
  const apiKey = KEY_ENV[provider] ? env[KEY_ENV[provider]!] : undefined;
  const inst = createProvider({ provider, apiKey, model: env.LIFEFLOW_MODEL });
  const sink = new InMemoryEvalSink();
  const scores: CaseScore[] = [];
  const latencies: number[] = [];
  let validationFailures = 0;
  let otherErrors = 0;
  let model = provider;

  for (const cse of DATASET) {
    const t0 = performance.now();
    try {
      const out = await extract(inst, { parts: [{ kind: 'text', text: cse.input }] }, { sink, inputMethod: 'text' });
      latencies.push(performance.now() - t0);
      model = out.meta.model;
      scores.push(scoreCase(cse, out.result.items));
    } catch (err) {
      latencies.push(performance.now() - t0);
      if (err instanceof SchemaValidationError) validationFailures++;
      else otherErrors++;
      scores.push(scoreCase(cse, [])); // unscored extraction counts as full miss
    }
  }

  const tokensIn = sink.extractions.reduce((a, t) => a + (t.tokensIn ?? 0), 0);
  const tokensOut = sink.extractions.reduce((a, t) => a + (t.tokensOut ?? 0), 0);
  const price = priceFor(model);
  const costUsd = (tokensIn / 1e6) * price.inPerM + (tokensOut / 1e6) * price.outPerM;
  const sorted = [...latencies].sort((a, b) => a - b);

  return {
    provider, model,
    agg: aggregate(scores, validationFailures),
    tokensIn, tokensOut, costUsd,
    latency: { meanMs: Math.round(sorted.reduce((a, b) => a + b, 0) / (sorted.length || 1)), p50: percentile(sorted, 50), p95: percentile(sorted, 95) },
    otherErrors,
  };
}

function recommend(results: Result[]): Result {
  const score = (r: Result) => r.agg.f1 * 0.55 + r.agg.fieldAccuracy * 0.45 - (r.agg.validationFailures / Math.max(1, r.agg.cases)) * 0.5;
  return [...results].sort((a, b) => score(b) - score(a))[0]!;
}

function pct(n: number): string { return (n * 100).toFixed(1) + '%'; }

function buildReport(results: Result[]): string {
  const rec = recommend(results);
  const rows = results.map((r) =>
    `| ${r.provider} (${r.model}) | ${pct(r.agg.f1)} | ${pct(r.agg.fieldAccuracy)} | ${pct(r.agg.recall)} | ${pct(r.agg.precision)} | ${r.agg.validationFailures} | ${r.agg.ece.toFixed(3)} | ${r.agg.calibrationGap >= 0 ? '+' : ''}${r.agg.calibrationGap.toFixed(2)} | ${r.tokensIn + r.tokensOut} | $${r.costUsd.toFixed(4)} | ${r.latency.p50}/${r.latency.p95} |`,
  );
  const onlyStub = results.length === 1 && results[0]!.provider === 'stub';
  return [
    '# LifeFlow AI — Provider Benchmark Report',
    '',
    `Dataset: **${DATASET.length}** messy routine descriptions · 1 run each · generated by \`npm run bench\`.`,
    '',
    '| Provider (model) | Item F1 | Field acc | Recall | Precision | Valid. fails | ECE | Calib. gap | Tokens | Cost | Latency p50/p95 (ms) |',
    '|---|---|---|---|---|---|---|---|---|---|---|',
    ...rows,
    '',
    '**Metric notes**',
    '- *Item F1* — did it find the right items (by title keyword)?',
    '- *Field acc* — of matched items, fraction with correct type/category/recurrence/time.',
    '- *ECE* — expected calibration error (lower = stated confidence matches reality).',
    '- *Calib. gap* — mean confidence − precision (positive = overconfident).',
    '- *Cost* — estimated from token usage × editable price table in `src/ai/registry.ts`.',
    '',
    `## Recommendation: **${rec.provider}** (${rec.model})`,
    '',
    onlyStub
      ? '> Only the deterministic **stub** baseline ran — no provider API keys were configured. ' +
        'This proves the harness end-to-end and gives a floor to beat. Set `ANTHROPIC_API_KEY` / ' +
        '`OPENAI_API_KEY` / `GEMINI_API_KEY` and re-run to compare real models. The prior recommendation ' +
        '(see `docs/AI_PROVIDER_COMPARISON.md`) is **Gemini Flash** for the OCR/cost/latency profile.'
      : `Chosen by composite of item-F1, field accuracy, and validation reliability across ${DATASET.length} cases. ` +
        'Switching is one line: `LIFEFLOW_PROVIDER=' + rec.provider + '`.',
    '',
    '_Report regenerated by `npm run bench`; do not hand-edit._',
    '',
  ].join('\n');
}

// ---- main ----
const providers = selectedProviders();
console.log(`Benchmarking ${providers.join(', ')} over ${DATASET.length} cases…\n`);
const results: Result[] = [];
for (const p of providers) {
  process.stdout.write(`  ${p}… `);
  results.push(await runProvider(p));
  console.log('done');
}

const report = buildReport(results);
await writeFile(join(HERE, 'report.md'), report);
await writeFile(join(HERE, 'report.json'), JSON.stringify({ dataset: DATASET.length, results }, null, 2));

console.log('\n' + report);
console.log(`\nWrote bench/report.md and bench/report.json`);
